In [ ]:
import numpy as np

arr= np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40,50,60])
print(s.describe())
print(s.mean())
print(s.sum())
print(s.min())
print(s.max())



count     6.000000
mean     35.000000
std      18.708287
min      10.000000
25%      22.500000
50%      35.000000
75%      47.500000
max      60.000000
dtype: float64
35.0
210
10
60


In [ ]:
s1=pd.Series([11,12,13,14,15])
print(s1.map(lambda x : x**2))
s2=pd.Series([29,27,11,27,49,1,10000])
print(s2.sort_values())
print(s2.drop(2))
print(s2.duplicated())


0    121
1    144
2    169
3    196
4    225
dtype: int64
5        1
2       11
3       27
1       27
0       29
4       49
6    10000
dtype: int64
0       29
1       27
3       27
4       49
5        1
6    10000
dtype: int64
0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool


In [ ]:
####handle missing values
import numpy as np
s3=pd.Series([10,np.nan,18,19,np.nan,28])
print(s3.isnull())
print(s3.notnull())
print(s3.fillna(22))
print(s3.dropna())


0    False
1     True
2    False
3    False
4     True
5    False
dtype: bool
0     True
1    False
2     True
3     True
4    False
5     True
dtype: bool
0    10.0
1    22.0
2    18.0
3    19.0
4    22.0
5    28.0
dtype: float64
0    10.0
2    18.0
3    19.0
5    28.0
dtype: float64


In [ ]:
import numpy as np
import pandas as pd
s4=pd.Series([19,20,21,22,23,24,25])
print(s4.iloc[1])
print(s4.iloc[-2])
print(s4.loc[3])
print(s4[s4>=21])

20
24
22
2    21
3    22
4    23
5    24
6    25
dtype: int64


In [ ]:
import numpy as np
arr = np.arange(2,20,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
arr=([1,2,3,4])
sum=np.sum(arr)
mean=np.mean(arr)
print(mean)
print(sum)
print(np.max(arr))
print(np.min(arr))

2.5
10
4
1


In [ ]:
arr = np.array([[1.5, 2, 3], [4, 5, 6]])
shape=np.shape(arr)
size=np.size(arr)
print(size)
print(arr.ndim)
print(arr.dtype)

6
2
float64


In [ ]:
arr = np.array([[1.5, 2, 3], [4, 5, 6]])
mult=arr*2
print(mult)

[[ 3.  4.  6.]
 [ 8. 10. 12.]]


In [ ]:
arr=np.zeros((5,2))
sh=np.shape(arr)
print(sh)
print(arr)

(5, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
